### ISSUE TITLE
Broken app data root folder path determination for OS X

### ISSUE THREAD

**Issue by tobiasmuecksch** [s-a/time-track#1]
Hey there,

when I try to create a project, the following error is shown:

> Error: EACCES: permission denied, mkdir '/Users/tmueckschLibrary'

My operating system is Mac OS X 10.11.3

Here is a screenshot:
![Screenshot](http://cl.ly/3h432n1c3R0j/Bildschirmfoto%202016-02-16%20um%2009.55.08.png)

I guess for some reason there is no slash in prepended in front of "Library" is truncated. I'm going to have a look at the code. Maybe I can fix it.

**Comment by s-a** [comment]
I ve just deployed v1.0.4 to npm wich includes your fixed code.

**Comment by TimVold** [comment]
I just pulled and installed v1.0.4 on my El Capitan v10.11.3.
I now get an error:
         env: node\r: No such file or directory

**Comment by s-a** [comment]
Could you please paster the error stacktrace?

**Comment by tobiasmuecksch** [comment]
I'm sorry to hear that. Is the the stack trace in the screenshot not sufficient?

**Comment by tobiasmuecksch** [comment]
I'd like to debug the program further, how do you test the cli without installing it globally?
`node lib/index.js -s test` didn't work for me.

**Comment by s-a** [comment]
`node lib/cli.js -s test`

**Comment by s-a** [comment]
we do not know if @TimVold hits the same problem?

**Comment by tobiasmuecksch** [comment]
Well that is interesting. Version 1.0.4 returns the same error `env: node\r: No such file or directory` if installed via npm. But my fork works if started with `node lib/cli.js -s test`.

**Comment by TimVold** [comment]
Sorry gents, I was off in a meeting on my day job.  What can I do to help?
Apologies, didn't intend for my post to be a "drive-by".

**Comment by TimVold** [comment]
Here's my stacktrace.

$ node lib/cli.js -s test

module.js:338
    throw err;
          ^
Error: Cannot find module '~./lib/cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by tobiasmuecksch** [comment]
When I directly clone this repository and start it with `node lib/cli.js -s test` it works like a charm. I guess there could be something going wrong during installation via npm.

**Comment by tobiasmuecksch** [comment]
You need to perform `npm install` first.

**Comment by tobiasmuecksch** [comment]
@TimVold What directory are you in with your console?

`/Volumes/home/sq3952na/src/orgmaint` doesn't seem to be a clone of time-tracker. In order to execute `node lib/cli.js -s test` you need to have cloned time-tracker before.

**Comment by TimVold** [comment]
So, doing an:
npm install time-track@1.0.4 -g
is not sufficient?

**Comment by TimVold** [comment]
That long directory, of which you ask, is simply a source directory.  If I sit in my user.home dir, and "npm install time-track@1.0.4 -g" is still get the same stack trace.  I'll try a direct git clone, now, as you note has worked for you.

**Comment by tobiasmuecksch** [comment]
@TimVold Well it should be sufficient. But for some reason the global installation through npm won't work at the moment. In order to fix the code, I've forked this repository. If you have forked (or cloned) it you can execute `node lib/cli.js -s test`. But you have to execute `npm install` while being in the newly cloned folder first.

**Comment by tobiasmuecksch** [comment]
I'm going to open a new issue, as the problem we are currently discussing is different from the one described in the initial post.

**Comment by TimVold** [comment]
Ok, did:
   1) git clone git@github.com:s-a/time-track.git
   2) cd time-track
   3) npm install
   4) node lib/cli.js -s test
       Result of #4 was:      \Switched to project test

**Comment by tobiasmuecksch** [comment]
Well then it works on your machine too. That means there might be a problem with the installation.

**Comment by tobiasmuecksch** [comment]
@TimVold @s-a see issue #3

**Comment by TimVold** [comment]
It seems so; but I'm still coming off what passes for the npm learning curve.  I think you are correct that it is a separate issue.

If I understand correctly, I should be able to do a "npm install -g" from within the time-track src dir that I got from your repo, built, and tested successfully.  Correct?  That install command completes without apparent error; but I can't "tt -s test" from outside the time-track src dir.

Taking a look at issue #3 now.

**Comment by tobiasmuecksch** [comment]
@TimVold Yes, it won't work yet. See issue #3, I already found what might be causing the issue. Im currently trying to fix it.

**Comment by tobiasmuecksch** [comment]
@TimVold I found a fix. Clone the latest version of my fork and then install it with `npm install -g`. Then time-track finally works on Mac OS X too :+1:
