### ISSUE TITLE
Won't work if installed via npm, but works if cloned (Mac OS X)

### ISSUE THREAD

**Issue by tobiasmuecksch** [s-a/time-track#3]
As discussed in issue #1, after the installation of time-track through npm time-track won't work on Mac OSX. 

If the command `tt` is performed the following error is returned:

> env: node\r: No such file or directory

After some research I found the problem with the cli.js file. In line 1, there is a shebang:
`#!/usr/bin/env node`

I assume @s-a is programming on Windows. As described in this stackoverflow discussion there is a problem with the new-lines inserted by windows:
[Node script executable not working on Mac : env: node\r: No such file or directory](http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo)

I will issue a pull request with the fix.

**Comment by s-a** [comment]
just published v1.0.5 where I added tests that all code files are saved with unix style line endings https://travis-ci.org/s-a/time-track/jobs/109649472#L308. This should fix it for mac os. @tobiasmuecksch can you confirm that https://github.com/s-a/time-track/releases/tag/v1.0.5 work for you from npm?

**Comment by tobiasmuecksch** [comment]
Thank you for your effort. Version 1.0.5 works on Mac OS X as expected.
:+1:

**Comment by s-a** [comment]
OK . Thank you very much for figuring this out :hand:
